// Test-only editor projection. Production snapshots come from the Foundation adapter.
import {
  EDITOR_AGENT_CONTRACT_VERSION,
  type EditorClip,
  type EditorCompositionSnapshot,
  type EditorTrack,
} from '@/lib/creative-studio/editor-agent/contracts'

const DEFAULT_TRANSFORM = {
  x: 0,
  y: 0,
  scale: 1,
  rotation: 0,
  opacity: 1,
} as const

function clip(
  input: Omit<EditorClip, 'transform' | 'locked' | 'status'> & {
    transform?: Partial<EditorClip['transform']>
    locked?: boolean
    status?: EditorClip['status']
  },
): EditorClip {
  const { transform, locked, status, ...rest } = input
  return {
    ...rest,
    transform: { ...DEFAULT_TRANSFORM, ...transform },
    locked: locked ?? false,
    status: status ?? 'ready',
  }
}

export function createEditorFixtureSnapshot(): EditorCompositionSnapshot {
  const tracks: EditorTrack[] = [
    {
      id: 'track-video',
      kind: 'video',
      label: 'Video',
      muted: false,
      locked: false,
      clips: [
        clip({
          id: 'clip-hero',
          trackId: 'track-video',
          kind: 'video',
          label: 'Opening product shot',
          startSec: 0,
          endSec: 4.8,
          sourceStartSec: 0,
          sourceEndSec: 4.8,
          assetId: 'asset-hero',
          assetVersionId: 'asset-hero-v6',
          text: null,
          volume: 0.7,
        }),
        clip({
          id: 'clip-family',
          trackId: 'track-video',
          kind: 'video',
          label: 'Family story',
          startSec: 4.8,
          endSec: 13.2,
          sourceStartSec: 0,
          sourceEndSec: 8.4,
          assetId: 'asset-family',
          assetVersionId: 'asset-family-v3',
          text: null,
          volume: 0.65,
        }),
        clip({
          id: 'clip-close',
          trackId: 'track-video',
          kind: 'video',
          label: 'Detail close',
          startSec: 13.2,
          endSec: 24,
          sourceStartSec: 0,
          sourceEndSec: 10.8,
          assetId: 'asset-detail',
          assetVersionId: 'asset-detail-v2',
          text: null,
          volume: 0.55,
        }),
      ],
    },
    {
      id: 'track-overlay',
      kind: 'overlay',
      label: 'Image / Overlay',
      muted: false,
      locked: false,
      clips: [
        clip({
          id: 'overlay-logo',
          trackId: 'track-overlay',
          kind: 'image',
          label: 'ALMA wordmark',
          startSec: 0,
          endSec: 24,
          sourceStartSec: 0,
          sourceEndSec: 24,
          assetId: 'asset-wordmark',
          assetVersionId: 'asset-wordmark-v4',
          text: null,
          volume: 0,
          transform: { x: 0, y: -0.76, scale: 0.42, opacity: 0.92 },
        }),
      ],
    },
    {
      id: 'track-caption',
      kind: 'caption',
      label: 'Captions',
      muted: false,
      locked: false,
      clips: [
        clip({
          id: 'caption-primary',
          trackId: 'track-caption',
          kind: 'caption',
          label: 'ঈদের নতুন গল্প',
          startSec: 2.4,
          endSec: 8.4,
          sourceStartSec: 2.4,
          sourceEndSec: 8.4,
          assetId: null,
          assetVersionId: null,
          text: 'ঈদের নতুন গল্প',
          volume: 0,
          transform: { x: 0, y: 0.66, scale: 1, opacity: 1 },
        }),
      ],
    },
    {
      id: 'track-voice',
      kind: 'voice',
      label: 'Voice',
      muted: false,
      locked: false,
      clips: [
        clip({
          id: 'voice-owner-v3',
          trackId: 'track-voice',
          kind: 'voice',
          label: 'Owner voice · active v3',
          startSec: 0.8,
          endSec: 22.8,
          sourceStartSec: 0,
          sourceEndSec: 22,
          assetId: 'asset-voice',
          assetVersionId: 'voice-version-v3',
          text: null,
          volume: 1,
        }),
      ],
    },
    {
      id: 'track-music',
      kind: 'music',
      label: 'Music',
      muted: false,
      locked: false,
      clips: [
        clip({
          id: 'music-eid-pulse',
          trackId: 'track-music',
          kind: 'music',
          label: 'Eid pulse',
          startSec: 0,
          endSec: 24,
          sourceStartSec: 0,
          sourceEndSec: 24,
          assetId: 'asset-music',
          assetVersionId: 'asset-music-v2',
          text: null,
          volume: 0.18,
        }),
      ],
    },
    {
      id: 'track-sfx',
      kind: 'sfx',
      label: 'SFX',
      muted: false,
      locked: false,
      clips: [
        clip({
          id: 'sfx-fabric',
          trackId: 'track-sfx',
          kind: 'sfx',
          label: 'Soft fabric movement',
          startSec: 0.8,
          endSec: 2.6,
          sourceStartSec: 0,
          sourceEndSec: 1.8,
          assetId: 'asset-sfx',
          assetVersionId: 'asset-sfx-v1',
          text: null,
          volume: 0.68,
        }),
      ],
    },
  ]

  return {
    contractVersion: EDITOR_AGENT_CONTRACT_VERSION,
    scope: {
      brandProfileId: 'brand-alma-lifestyle',
      projectId: 'project-coral-eid',
      compositionId: 'composition-coral-reel',
    },
    name: 'Coral Panjabi · Eid Reel',
    brandName: 'ALMA Lifestyle',
    projectName: 'Coral Panjabi Launch',
    recipeName: 'Editorial Warm',
    recipeVersion: 7,
    productCode: 'AL-EID-042',
    productName: 'Coral Embroidered Panjabi',
    version: 12,
    concurrencyToken: 'fixture-v12',
    canvas: {
      aspectRatio: '9:16',
      width: 1080,
      height: 1920,
      durationSec: 24,
      safeZone: true,
      background: '#e07a5f',
    },
    tracks,
    assets: [
      {
        assetId: 'asset-hero',
        assetVersionId: 'asset-hero-v6',
        title: 'Coral Panjabi · Hero',
        mediaType: 'image',
        previewUrl: null,
        storagePath: 'creative/fixture/coral-hero.jpg',
        status: 'approved',
        provider: 'fashn',
        engine: 'product-to-model',
        recipeVersion: 7,
        costBdt: 11,
        qcLabel: 'Identity 96 · Garment 94',
        artifact: {
          kind: 'original',
          storagePath: 'creative/fixture/coral-hero.jpg',
          width: 1080,
          height: 1350,
          pixelCount: 1_458_000,
          format: 'jpeg',
          mimeType: 'image/jpeg',
          byteSize: 482_104,
          sha256: 'fixture-sha256-coral-hero',
          requestedTier: '1k',
          requestedAspectRatio: '4:5',
          actualTier: '1k',
          validation: 'verified',
          validationErrors: [],
          expected: null,
          provider: 'fashn',
          model: 'product-to-model',
          sourceKind: 'provider_original',
          transformVersion: null,
          transform: null,
        },
        referenceContract: {
          version: 1,
          mode: 'product_to_model',
          requestedEngine: 'fashn',
          actualModel: 'product-to-model',
          bindings: [
            {
              role: 'product',
              path: 'creative/fixture/product.jpg',
              source: 'uploaded',
              sourceId: 'AL-EID-042',
              required: true,
            },
            {
              role: 'person',
              path: 'creative/fixture/model.jpg',
              source: 'saved_model',
              sourceId: 'model-owner-v4',
              required: false,
            },
          ],
        },
      },
      {
        assetId: 'asset-family',
        assetVersionId: 'asset-family-v3',
        title: 'Father + Son · Select 02',
        mediaType: 'video',
        previewUrl: null,
        storagePath: 'creative/fixture/family-story.mp4',
        status: 'ready',
        provider: 'alma-local',
        engine: 'owned-footage-recipe',
        recipeVersion: 5,
        costBdt: 0,
        qcLabel: 'Source verified',
        artifact: null,
        referenceContract: null,
      },
      {
        assetId: 'asset-detail',
        assetVersionId: 'asset-detail-v2',
        title: 'Embroidery detail',
        mediaType: 'video',
        previewUrl: null,
        storagePath: 'creative/fixture/detail.mp4',
        status: 'ready',
        provider: 'alma-local',
        engine: 'owned-footage-recipe',
        recipeVersion: 7,
        costBdt: 0,
        qcLabel: 'Source verified',
        artifact: null,
        referenceContract: null,
      },
      {
        assetId: 'asset-music',
        assetVersionId: 'asset-music-v2',
        title: 'Eid pulse · 24 sec',
        mediaType: 'music',
        previewUrl: null,
        storagePath: 'creative/fixture/eid-pulse.wav',
        status: 'approved',
        provider: 'alma-library',
        engine: 'owner-approved-audio',
        recipeVersion: null,
        costBdt: 0,
        qcLabel: 'Licensed · owner approved',
        artifact: null,
        referenceContract: null,
      },
    ],
    review: {
      state: 'changes_requested',
      approvedVersion: 11,
      publishReady: false,
      openComments: 3,
    },
    activity: [
      {
        id: 'activity-review-v11',
        kind: 'review',
        actorName: 'Reviewer',
        summary: 'Opening caption timing needs revision.',
        version: 11,
        createdAt: '2026-07-25T17:42:00.000Z',
        operationIds: [],
      },
      {
        id: 'activity-system-v12',
        kind: 'system',
        actorName: 'Creative Studio',
        summary: 'Composition projected from verified asset versions.',
        version: 12,
        createdAt: '2026-07-25T18:00:00.000Z',
        operationIds: [],
      },
    ],
    canUndo: false,
    canRedo: false,
    latestAgentBatchId: null,
    canRollbackLatestAgentBatch: false,
  }
}
