/**
 * G09 / SPEC-081 — Capability catalog generator (DEV-TIME ONLY).
 *
 * Derives one Capability per G08 tool domain from the decoupled G08 manifest
 * loader, so the capability control plane is grounded in the real 326-tool
 * surface rather than hand-waved. Emits `catalog.generated.ts` (pure data, no
 * monolith/prisma/network/model — INV-01). Later G09 specs validate this catalog
 * against their facet rules.
 *
 * Run: npx tsx --tsconfig tsconfig.json \
 *        src/agent/capabilities/scripts/build-catalog.ts
 */
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { domains, manifestsForDomain } from '@/agent/tools/manifests/loader'
import type { ToolManifest, SideEffectKind } from '@/agent/tools/manifests/manifest.schema'
import type { Capability } from '../capability.schema'

const RISK_ORDER = { low: 0, medium: 1, high: 2 } as const

function deriveCapability(key: string, manifests: readonly ToolManifest[]): Capability {
  const toolNames = manifests.map((m) => m.name).slice().sort()
  const modes = new Set(manifests.map((m) => m.capability.mode))
  const effects = new Set<SideEffectKind>(manifests.flatMap((m) => m.capability.sideEffects))
  const pools = [...new Set(manifests.flatMap((m) => m.routing.pools))].sort()
  const groups = [...new Set(manifests.flatMap((m) => m.routing.groups))].sort()
  const hasWrite = modes.has('write') || modes.has('stage')
  const maxRisk = manifests.reduce<'low' | 'medium' | 'high'>((acc, m) => (RISK_ORDER[m.capability.risk] > RISK_ORDER[acc] ? m.capability.risk : acc), 'low')

  // Intents: every capability can be queried; write-bearing ones can be managed.
  const intents = hasWrite ? [`query_${key}`, `manage_${key}`] : [`query_${key}`]
  const intentClasses = hasWrite ? (['command', 'task', 'question'] as const) : (['question'] as const)

  // Permission scope — fail-closed to 'owner' unless the whole capability is a
  // narrower surface. Customer only if EVERY tool is customer-safe; staff only if
  // every tool is staff-pool and none owner-only.
  const allCustomer = manifests.every((m) => m.routing.pools.includes('customer'))
  const allStaff = manifests.every((m) => m.routing.pools.includes('staff'))
  const scope = allCustomer ? 'customer' : allStaff ? 'staff' : 'owner'

  // Cost tier — heavy if any model invocation; standard if external/high-risk; else light.
  const heavy = effects.has('model_invocation')
  const external = effects.has('external_message') || effects.has('external_api_write') || effects.has('money_movement') || effects.has('browser_action')
  const tier = heavy ? 'heavy' : external || maxRisk === 'high' ? 'standard' : 'light'
  const costClass = tier === 'heavy' ? 'premium' : tier === 'standard' ? 'metered' : 'free'

  return {
    id: `cap.${key}`,
    key,
    title: key.replace(/_/g, ' '),
    description: `Capability for the ${key} domain (${manifests.length} tools).`,
    status: 'active',
    intents,
    intentClasses: [...intentClasses],
    toolNames,
    permission: { scope, minRole: scope, defaultDecision: 'deny' },
    cost: { tier, class: costClass },
    runtime: { groups, pools },
    owner: { team: '@alma/agent', zonePrefix: 'src/agent/tools' },
    health: { status: 'healthy', killSwitch: false },
  }
}

function build(): Capability[] {
  return domains()
    .map((d) => deriveCapability(d, manifestsForDomain(d)))
    .sort((a, b) => a.key.localeCompare(b.key))
}

function render(caps: Capability[]): string {
  const lines: string[] = []
  lines.push('/**')
  lines.push(' * GENERATED by scripts/build-catalog.ts (G09 / SPEC-081). DO NOT EDIT.')
  lines.push(' *')
  lines.push(' * One capability per G08 tool domain, derived from the decoupled manifest')
  lines.push(' * loader. Pure data; no monolith/prisma/network/model (INV-01).')
  lines.push(' */')
  lines.push("import type { Capability } from './capability.schema'")
  lines.push('')
  lines.push('export const CAPABILITY_CATALOG: readonly Capability[] = [')
  for (const c of caps) lines.push(`  ${JSON.stringify(c)},`)
  lines.push(']')
  lines.push('')
  return lines.join('\n')
}

function main(): void {
  const caps = build()
  const target = resolve(process.cwd(), 'src/agent/capabilities/catalog.generated.ts')
  writeFileSync(target, render(caps), 'utf8')
  // eslint-disable-next-line no-console
  console.error(`[build-catalog] ${caps.length} capabilities → ${target}`)
}

main()
