//
//  AccessContractTests.swift
//  ALMA ERP — proves AlmaAccess.swift (the native role × business port) answers
//  EXACTLY like the web's src/lib/roles.ts + businesses.ts, for every role ×
//  business × path in ios/access-contract.json (generated by
//  `npm run access-contract:update`). A failing case names the drifted rule.
//

import XCTest
@testable import App

final class AccessContractTests: XCTestCase {

    private struct Contract: Decodable {
        struct Business: Decodable {
            let id: String, name: String, shortName: String, tagline: String, brandInitial: String, homePath: String
        }
        struct NavEntry: Decodable { let href: String, icon: String, label: String }
        let version: Int
        let roles: [String]
        let businesses: [Business]
        let paths: [String]
        let routeAllowed: [String: [String: Bool]]
        let matrix: [String: [String: Bool]]
        let nav: [String: [NavEntry]]
        let filteredNav: [String: [String]]
        let roleHome: [String: String]
        let capabilities: [String: [String]]
        let businessAccessSamples: [String: [String]]
    }

    private static func loadContract() throws -> Contract {
        // ios/App/AppParityV2Tests/AccessContractTests.swift → ios/access-contract.json
        let url = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()   // AppParityV2Tests
            .deletingLastPathComponent()   // App
            .deletingLastPathComponent()   // ios
            .appendingPathComponent("access-contract.json")
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(Contract.self, from: data)
    }

    func testRolesAndBusinessesEnumerated() throws {
        let c = try Self.loadContract()
        XCTAssertEqual(c.roles, AlmaRole.allCases.map(\.rawValue))
        XCTAssertEqual(c.businesses.map(\.id), AlmaBusinessId.all.map(\.rawValue))
        for b in c.businesses {
            let id = try XCTUnwrap(AlmaBusinessId(rawValue: b.id))
            XCTAssertEqual(id.name, b.name, b.id)
            XCTAssertEqual(id.shortName, b.shortName, b.id)
            XCTAssertEqual(id.tagline, b.tagline, b.id)
            XCTAssertEqual(id.brandInitial, b.brandInitial, b.id)
            XCTAssertEqual(id.homePath, b.homePath, b.id)
        }
    }

    func testIsRouteAllowedMatchesWeb() throws {
        let c = try Self.loadContract()
        for (bizRaw, rows) in c.routeAllowed {
            let biz = try XCTUnwrap(AlmaBusinessId(rawValue: bizRaw))
            for (path, expected) in rows {
                XCTAssertEqual(AlmaAccess.isRouteAllowed(path, business: biz), expected,
                               "isRouteAllowed(\(path), \(bizRaw))")
            }
        }
    }

    func testIsPathAllowedForRoleMatchesWeb() throws {
        let c = try Self.loadContract()
        var checked = 0
        for (key, rows) in c.matrix {
            let parts = key.split(separator: "|").map(String.init)
            let role = try XCTUnwrap(AlmaRole(rawValue: parts[0]))
            let biz = try XCTUnwrap(AlmaBusinessId(rawValue: parts[1]))
            for (path, expected) in rows {
                XCTAssertEqual(AlmaAccess.isPathAllowedForRole(path, role: role, business: biz), expected,
                               "isPathAllowedForRole(\(path), \(role), \(biz))")
                checked += 1
            }
        }
        XCTAssertGreaterThan(checked, 1000, "matrix should cover every role × business × path")
    }

    func testNavListsMatchWeb() throws {
        let c = try Self.loadContract()
        for (bizRaw, entries) in c.nav {
            let biz = try XCTUnwrap(AlmaBusinessId(rawValue: bizRaw))
            let native = AlmaNav.nav(for: biz)
            XCTAssertEqual(native.map(\.href), entries.map(\.href), "nav hrefs \(bizRaw)")
            XCTAssertEqual(native.map(\.label), entries.map(\.label), "nav labels \(bizRaw)")
            XCTAssertEqual(native.map(\.icon), entries.map(\.icon), "nav icons \(bizRaw)")
        }
    }

    func testFilteredNavMatchesWeb() throws {
        let c = try Self.loadContract()
        for (key, hrefs) in c.filteredNav {
            let parts = key.split(separator: "|").map(String.init)
            let role = try XCTUnwrap(AlmaRole(rawValue: parts[0]))
            let biz = try XCTUnwrap(AlmaBusinessId(rawValue: parts[1]))
            XCTAssertEqual(AlmaAccess.nav(role: role, business: biz).map(\.href), hrefs, "filteredNav \(key)")
        }
    }

    func testRoleHomeMatchesWeb() throws {
        let c = try Self.loadContract()
        for (key, home) in c.roleHome {
            let parts = key.split(separator: "|").map(String.init)
            let role = try XCTUnwrap(AlmaRole(rawValue: parts[0]))
            let biz = try XCTUnwrap(AlmaBusinessId(rawValue: parts[1]))
            XCTAssertEqual(AlmaAccess.roleHomePath(role: role, business: biz), home, "roleHome \(key)")
        }
    }

    func testCapabilitiesMatchWeb() throws {
        let c = try Self.loadContract()
        XCTAssertEqual(Set(c.capabilities.keys), Set(AlmaCapability.allCases.map(\.rawValue)))
        for (capRaw, roles) in c.capabilities {
            let cap = try XCTUnwrap(AlmaCapability(rawValue: capRaw))
            XCTAssertEqual(cap.roles.map(\.rawValue), roles, "capability \(capRaw)")
            for role in AlmaRole.allCases {
                XCTAssertEqual(AlmaAccess.can(role, cap), roles.contains(role.rawValue), "can(\(role), \(capRaw))")
            }
        }
    }

    func testBusinessAccessParsingMatchesWeb() throws {
        let c = try Self.loadContract()
        for (raw, expected) in c.businessAccessSamples {
            XCTAssertEqual(AlmaBusinessId.parseAccess(raw).map(\.rawValue), expected, "parseAccess(\"\(raw)\")")
        }
    }

    func testRoleNormalizationMatchesWeb() {
        XCTAssertEqual(AlmaRole.normalize(" super admin "), .SUPER_ADMIN)
        XCTAssertEqual(AlmaRole.normalize("hr"), .HR)
        XCTAssertEqual(AlmaRole.normalize("bogus"), .VIEWER)
        XCTAssertEqual(AlmaRole.normalize(nil), .VIEWER)
    }

    /// Every web nav href must be reachable natively: either a tab candidate or a
    /// More-menu row — otherwise a role could be granted a page the app never offers.
    func testEveryWebNavHrefIsOfferedByTheShell() {
        let offered = AlmaShellCatalog.allOfferedHrefs
        for href in AlmaNav.allHrefs {
            XCTAssertTrue(offered.contains(href), "web nav href \(href) is not offered by the iOS shell (tab or More row)")
        }
    }

    /// Codex P2 (PR #835): a business-scoped entity link is gated under ITS
    /// business, so an HR user currently in Trading may still open a Lifestyle
    /// employee link (and the forged Trading selector is refused by the router).
    @MainActor
    func testScopedEntityLinkIsGatedUnderItsOwnBusiness() {
        let session = AlmaSession.shared
        session.applyFixture(role: .HR, access: AlmaBusinessId.all)
        session.setBusiness(.ALMA_TRADING)
        XCTAssertEqual(session.businessId, .ALMA_TRADING)
        XCTAssertTrue(session.canSee("/employees/EMP-1?business_id=ALMA_LIFESTYLE"))
        XCTAssertTrue(session.canSee("/trading/hr"))
        XCTAssertFalse(session.canSee("/orders/ALM-1?business_id=ALMA_LIFESTYLE"),
                       "HR has no Lifestyle orders page on the web either")
        // Coordinator passes the FULL path to the gate (Codex P2, round 2).
        if case .native = AlmaNavCoordinator.decide(
            path: "/employees/EMP-1?business_id=ALMA_LIFESTYLE", openWebForced: { _, _ in }) {
        } else {
            XCTFail("HR in Trading must open a Lifestyle employee entity link natively")
        }
        if case .denied = AlmaNavCoordinator.decide(
            path: "/orders/ALM-1?business_id=ALMA_LIFESTYLE", openWebForced: { _, _ in }) {
        } else {
            XCTFail("HR must be denied a Lifestyle order link")
        }
        // A forged selector is refused by the router (.unknown), never turned into
        // an access verdict — no fetch, no wrong screen, no "no access" message.
        if case .unknown = AlmaNavCoordinator.decide(
            path: "/employees/EMP-1?business_id=ALMA_TRADING", openWebForced: { _, _ in }) {
        } else {
            XCTFail("forged business selector must be refused as unknown")
        }
        session.setBusiness(.ALMA_LIFESTYLE)
        session.applyFixture(role: .SUPER_ADMIN, access: AlmaBusinessId.all)
    }

    /// Codex P1 (round 3): a legacy queryless employee link keeps the business the
    /// shell is in (Trading roster tap → Trading employee); a stamped Lifestyle
    /// selector still opens the Lifestyle record from inside Trading.
    @MainActor
    func testLegacyEmployeeLinkKeepsActiveBusiness() throws {
        let session = AlmaSession.shared
        session.applyFixture(role: .SUPER_ADMIN, access: AlmaBusinessId.all)
        session.setBusiness(.ALMA_TRADING)
        XCTAssertEqual(AlmaAccess.Context.currentId, "ALMA_TRADING")
        guard case .native(let legacy) = AlmaNavCoordinator.decide(path: "/employees/EMP-1", openWebForced: { _, _ in }) else {
            return XCTFail("legacy employee link must stay native")
        }
        XCTAssertEqual(try XCTUnwrap(legacy as? AlmaHostingController<EmployeesScreen>).rootView.businessId, "ALMA_TRADING")
        guard case .native(let stamped) = AlmaNavCoordinator.decide(
            path: "/employees/EMP-1?business_id=ALMA_LIFESTYLE", openWebForced: { _, _ in }) else {
            return XCTFail("stamped Lifestyle employee link must stay native")
        }
        XCTAssertEqual(try XCTUnwrap(stamped as? AlmaHostingController<EmployeesScreen>).rootView.businessId, "ALMA_LIFESTYLE")
        session.setBusiness(.ALMA_LIFESTYLE)
    }

    /// Codex P1 (round 6): Trading HR taps the queryless `/employees/{id}` links that
    /// Payroll / Approvals still emit. Web: proxy.ts judges `/employees/*` under the
    /// Lifestyle roots (path prefix, not cookie) → allowed; BusinessContext keeps
    /// Trading (`legacy` kind) → the page loads the Trading roster. Native must match.
    @MainActor
    func testTradingHrOpensLegacyEmployeeLinkLikeWeb() throws {
        let session = AlmaSession.shared
        session.applyFixture(role: .HR, access: AlmaBusinessId.all)
        session.setBusiness(.ALMA_TRADING)
        XCTAssertTrue(session.canSee("/employees/EMP-1"), "proxy.ts allows HR on /employees/* regardless of the active business")
        guard case .native(let vc) = AlmaNavCoordinator.decide(path: "/employees/EMP-1", openWebForced: { _, _ in }) else {
            return XCTFail("Trading HR legacy employee link must stay native, not .denied")
        }
        XCTAssertEqual(try XCTUnwrap(vc as? AlmaHostingController<EmployeesScreen>).rootView.businessId, "ALMA_TRADING")
        // The role rule itself is unchanged: a Trading STAFF user still has no employee page.
        session.applyFixture(role: .STAFF, access: AlmaBusinessId.all)
        session.setBusiness(.ALMA_TRADING)
        XCTAssertFalse(session.canSee("/employees/EMP-1"))
        if case .denied = AlmaNavCoordinator.decide(path: "/employees/EMP-1", openWebForced: { _, _ in }) {} else {
            XCTFail("Trading STAFF must be denied the employee page like the web redirect")
        }
        session.applyFixture(role: .SUPER_ADMIN, access: AlmaBusinessId.all)
        session.setBusiness(.ALMA_LIFESTYLE)
    }

    /// Tab bar composition per role × business — the owner-visible outcome.
    func testTabLayoutsPerRole() {
        func tabs(_ role: AlmaRole, _ biz: AlmaBusinessId) -> [String] {
            AlmaShellCatalog.tabHrefs(role: role, business: biz)
        }
        XCTAssertEqual(tabs(.SUPER_ADMIN, .ALMA_LIFESTYLE), ["/", "/orders", "/agent", "/approvals"])
        XCTAssertEqual(tabs(.ADMIN, .ALMA_LIFESTYLE), ["/", "/orders", "/approvals", "/invoice"])
        XCTAssertEqual(tabs(.STAFF, .ALMA_LIFESTYLE), ["/", "/orders", "/invoice", "/portal"])
        XCTAssertEqual(tabs(.HR, .ALMA_LIFESTYLE), ["/employees", "/attendance", "/payroll", "/portal"])
        XCTAssertEqual(tabs(.VIEWER, .ALMA_LIFESTYLE), ["/", "/orders", "/approvals", "/invoice"])
        XCTAssertEqual(tabs(.STAFF, .ALMA_TRADING), ["/trading", "/trading/accounts", "/trading/telegram", "/portal"])
        XCTAssertEqual(tabs(.SUPER_ADMIN, .ALMA_TRADING), ["/trading", "/agent", "/trading/accounts", "/approvals"])
        XCTAssertEqual(tabs(.SUPER_ADMIN, .CREATIVE_DIGITAL_IT), ["/digital", "/agent", "/digital/clients", "/approvals"])
        XCTAssertEqual(tabs(.HR, .ALMA_TRADING), ["/trading/hr", "/attendance", "/payroll", "/portal"])
        // Never more than four content tabs (+ More).
        for role in AlmaRole.allCases {
            for biz in AlmaBusinessId.all {
                XCTAssertLessThanOrEqual(tabs(role, biz).count, 4, "\(role) \(biz)")
                XCTAssertFalse(tabs(role, biz).isEmpty, "\(role) \(biz)")
            }
        }
    }

    /// Native twin of web `StaffWaGate`: locked only on a POSITIVE gate-on + not-opted-in
    /// answer, never when the number is missing, and fail-open on nil (Codex P2).
    @MainActor
    func testRoleDeskWaGateMatchesWebStaffWaGate() {
        typealias S = RoleDeskScreen.WaOptinStatus
        XCTAssertFalse(RoleDeskScreen.isLocked(nil))
        XCTAssertFalse(RoleDeskScreen.isLocked(S(gateEnabled: false, optedInToday: true, waNumberConfigured: true)))
        XCTAssertFalse(RoleDeskScreen.isLocked(S(gateEnabled: true, optedInToday: true, waNumberConfigured: true)))
        XCTAssertTrue(RoleDeskScreen.isLocked(S(gateEnabled: true, optedInToday: false, waNumberConfigured: true)))
        XCTAssertTrue(RoleDeskScreen.isLocked(S(gateEnabled: true, optedInToday: false, waNumberConfigured: nil)))
        XCTAssertFalse(RoleDeskScreen.isLocked(S(gateEnabled: true, optedInToday: false, waNumberConfigured: false)))
        XCTAssertFalse(RoleDeskScreen.isLocked(S(gateEnabled: true, optedInToday: nil, waNumberConfigured: true)))
    }
}
