/**
 * G08 / SPEC-071 — Monolithic registry inventory generator (DEV-TIME ONLY).
 *
 * The decomposed registry must NOT import the live monolith at runtime (that
 * would drag prisma / network / the whole tool surface into a module whose whole
 * point is to be deterministic and cheap — INV-01). Instead this generator runs
 * once at dev time, imports the monolith's authored metadata, and emits a static,
 * sorted, committed snapshot (`inventory.data.ts`) that the runtime registry reads
 * with zero coupling.
 *
 * This is the "generated" seam that later specs (SPEC-079) build on. It lives in
 * the owned zone `src/agent/tools/registry` and touches nothing else.
 *
 * Run:  npx tsx --tsconfig tsconfig.json \
 *         src/agent/tools/registry/scripts/build-inventory.ts
 *
 * The generator is deterministic: rows are sorted by name, group/pool lists are
 * sorted, and the same monolith input always produces byte-identical output.
 */
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
// Monolith metadata sources (read here, at dev time, NEVER at runtime).
import { TOOL_CLASSIFICATION } from '@/agent/tools/capability-classification'
import { TOOL_GROUPS } from '@/agent/tools/tool-groups'
import {
  TOOLS,
  TRADING_TOOLS,
  PERSONAL_SAFE_TOOLS,
  STAFF_SAFE_TOOLS,
  type AgentTool,
} from '@/agent/tools/registry'
import { CUSTOMER_SAFE_TOOLS } from '@/agent/tools/cs-registry'

interface RawRow {
  name: string
  domain: string | null
  mode: string | null
  risk: string | null
  groups: string[]
  pools: string[]
  hasSchema: boolean
}

function collect(): RawRow[] {
  const groupOf: Record<string, string[]> = {}
  for (const [g, tools] of Object.entries(TOOL_GROUPS)) {
    for (const t of tools as AgentTool[]) (groupOf[t.name] ??= []).push(g)
  }

  const poolSources: Array<[string, AgentTool[]]> = [
    ['lifestyle', TOOLS],
    ['trading', TRADING_TOOLS],
    ['personal', PERSONAL_SAFE_TOOLS],
    ['staff', STAFF_SAFE_TOOLS],
    ['customer', CUSTOMER_SAFE_TOOLS],
  ]
  const poolOf: Record<string, string[]> = {}
  const schemaOf: Record<string, boolean> = {}
  for (const [p, tools] of poolSources) {
    for (const t of tools) {
      ;(poolOf[t.name] ??= []).push(p)
      const props = (t.input_schema as { properties?: Record<string, unknown> } | undefined)?.properties
      schemaOf[t.name] = schemaOf[t.name] || Object.keys(props ?? {}).length > 0
    }
  }

  const names = new Set<string>([...Object.keys(TOOL_CLASSIFICATION), ...Object.keys(poolOf)])
  return [...names].sort().map((name) => {
    const c = TOOL_CLASSIFICATION[name]
    return {
      name,
      domain: c?.domain ?? null,
      mode: c?.mode ?? null,
      risk: c?.risk ?? null,
      groups: (groupOf[name] ?? []).slice().sort(),
      pools: (poolOf[name] ?? []).slice().sort(),
      hasSchema: schemaOf[name] ?? false,
    }
  })
}

function render(rows: RawRow[]): string {
  const groups = Object.keys(TOOL_GROUPS).slice().sort()
  const pools = ['customer', 'lifestyle', 'personal', 'staff', 'trading']
  const lines: string[] = []
  lines.push('/**')
  lines.push(' * GENERATED by scripts/build-inventory.ts (G08 / SPEC-071). DO NOT EDIT BY HAND.')
  lines.push(' *')
  lines.push(' * Static snapshot of the monolithic tool surface as it existed when the')
  lines.push(' * decomposition began. Pure data: zero runtime dependency on the monolith,')
  lines.push(' * prisma, the network or any model (INV-01). Regenerate with:')
  lines.push(' *   npx tsx --tsconfig tsconfig.json \\')
  lines.push(' *     src/agent/tools/registry/scripts/build-inventory.ts')
  lines.push(' */')
  lines.push("import type { InventoryRow } from './inventory.schema'")
  lines.push('')
  lines.push(`export const INVENTORY_SOURCE = 'src/agent/tools/registry.ts (+ pools/groups/classification)' as const`)
  lines.push(`export const INVENTORY_GROUPS = ${JSON.stringify(groups)} as const`)
  lines.push(`export const INVENTORY_POOLS = ${JSON.stringify(pools)} as const`)
  lines.push('')
  lines.push('export const INVENTORY_ROWS: readonly InventoryRow[] = [')
  for (const r of rows) {
    lines.push(`  ${JSON.stringify(r)},`)
  }
  lines.push(']')
  lines.push('')
  return lines.join('\n')
}

function main(): void {
  const rows = collect()
  const out = render(rows)
  const target = resolve(process.cwd(), 'src/agent/tools/registry/inventory.data.ts')
  writeFileSync(target, out, 'utf8')
  // eslint-disable-next-line no-console
  console.error(
    `[build-inventory] wrote ${rows.length} rows to ${target} ` +
      `(classified=${rows.filter((r) => r.domain).length}, pooled=${rows.filter((r) => r.pools.length).length})`,
  )
}

main()
