/**
 * G08 / SPEC-074 — IO schema registry generator (DEV-TIME ONLY).
 *
 * Guarantees the invariant "every manifest's inputSchemaId resolves" by emitting
 * one schema per manifest. Curated tools get a real strict schema (proving the
 * strict-validation path); the rest get a permissive default (`additionalProperties
 * true`) so migration from handler-owned schemas can proceed tool-by-tool without
 * false rejects. Reads only the decoupled manifest loader — no monolith.
 *
 * Run: npx tsx --tsconfig tsconfig.json \
 *        src/agent/tools/registry/scripts/build-io-schemas.ts
 */
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { ALL_MANIFESTS } from '@/agent/tools/manifests/loader'

/** Hand-authored strict schemas for representative tools (the strict path). */
const CURATED: Record<string, unknown> = {
  'memory.save_memory.input': {
    type: 'object',
    properties: {
      scope: { type: 'string', enum: ['personal', 'business', 'staff'] },
      key: { type: 'string' },
      content: { type: 'string' },
      pinned: { type: 'boolean' },
      duration: { type: 'string', enum: ['permanent', 'today', '7d', '30d'] },
    },
    required: ['scope', 'content'],
    additionalProperties: false,
  },
  'bills.add_bill.input': {
    type: 'object',
    properties: {
      name: { type: 'string' },
      amount: { type: 'number' },
      dueDay: { type: 'integer', minimum: 1, maximum: 31 },
    },
    required: ['name', 'amount'],
    additionalProperties: false,
  },
}

const DEFAULT_SCHEMA = { type: 'object', properties: {}, additionalProperties: true }

function build(): Record<string, unknown> {
  const out: Record<string, unknown> = {}
  const ids = [...ALL_MANIFESTS].map((m) => m.io.inputSchemaId).sort()
  for (const id of ids) {
    out[id] = CURATED[id] ?? DEFAULT_SCHEMA
  }
  return out
}

function render(map: Record<string, unknown>): string {
  const ids = Object.keys(map).sort()
  const lines: string[] = []
  lines.push('/**')
  lines.push(' * GENERATED by scripts/build-io-schemas.ts (G08 / SPEC-074). DO NOT EDIT.')
  lines.push(' *')
  lines.push(' * One JSON Schema per manifest inputSchemaId. Curated tools carry a strict')
  lines.push(' * schema; the rest use a permissive default pending per-tool migration. Pure')
  lines.push(' * data; sourced from the decoupled manifest loader (INV-01).')
  lines.push(' */')
  lines.push('export const IO_SCHEMAS: Readonly<Record<string, unknown>> = {')
  for (const id of ids) lines.push(`  ${JSON.stringify(id)}: ${JSON.stringify(map[id])},`)
  lines.push('}')
  lines.push('')
  return lines.join('\n')
}

function main(): void {
  const map = build()
  const target = resolve(process.cwd(), 'src/agent/tools/registry/io-schemas.generated.ts')
  writeFileSync(target, render(map), 'utf8')
  const curated = Object.keys(map).filter((id) => CURATED[id]).length
  // eslint-disable-next-line no-console
  console.error(`[build-io-schemas] ${Object.keys(map).length} schemas (${curated} curated) → ${target}`)
}

main()
