/**
 * POST /api/assistant/internal/generate-focus-plan
 * Generates the AI daily focus plan. Worker sends context data.
 *
 * Cost: the owner asked that the daily plan no longer burn Sonnet. This is an
 * OWNER-facing plan (not customer-facing), so it is generated by DeepSeek
 * (cheap). Claude is kept as a safety fallback — if DeepSeek is unavailable or
 * returns nothing, we fall back so the owner never gets a blank morning plan.
 */
import { NextRequest, NextResponse } from 'next/server'
import { verifyAgentInternalToken } from '@/lib/agent-internal-auth'
import Anthropic from '@anthropic-ai/sdk'
import { enforceClaudeOnlyModel } from '@/agent/lib/models/guard'
import { getModel } from '@/agent/lib/models/registry'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'
export const maxDuration = 30

const FOCUS_PLAN_MODEL_ID = 'or-deepseek-v4-flash'

function buildPrompt(context: string): string {
  return `You are a personal executive assistant for a business owner in Bangladesh. Based on the following context, create a focused daily plan in Bangla. Keep it concise (max 8 items), prioritize by urgency, and group into Morning/Afternoon/Evening. Use bullet points.

CONTEXT:
${context}

Reply ONLY with the daily plan in Bangla (no English, no preamble). Format: emoji + time block + items. End with one motivational line.`
}

/** Primary: DeepSeek via OpenRouter. Returns null on any problem so we can fall back. */
async function generateWithDeepSeek(prompt: string): Promise<string | null> {
  const key = process.env.OPENROUTER_API_KEY?.trim()
  if (!key) return null
  try {
    const apiModel = getModel(FOCUS_PLAN_MODEL_ID).apiModel
    const referer = process.env.APP_URL?.replace(/\/$/, '') ?? 'https://alma-erp-six.vercel.app'
    const res = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${key}`,
        'Content-Type': 'application/json',
        'HTTP-Referer': referer,
        'X-Title': 'ALMA ERP Agent',
      },
      body: JSON.stringify({
        model: apiModel,
        max_tokens: 600,
        messages: [{ role: 'user', content: prompt }],
      }),
      signal: AbortSignal.timeout(20_000),
    })
    if (!res.ok) return null
    const data = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> }
    const text = data?.choices?.[0]?.message?.content
    return typeof text === 'string' && text.trim() ? text.trim() : null
  } catch {
    return null
  }
}

/** Safety fallback: Claude (locked model). */
async function generateWithClaude(prompt: string): Promise<string> {
  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) return ''
  const anthropic = new Anthropic({ apiKey, timeout: 25_000 })
  const response = await anthropic.messages.create({
    model: enforceClaudeOnlyModel(),
    max_tokens: 600,
    messages: [{ role: 'user', content: prompt }],
  })
  return response.content[0]?.type === 'text' ? response.content[0].text : ''
}

export async function POST(req: NextRequest) {
  const auth = req.headers.get('authorization') ?? ''
  const token = auth.startsWith('Bearer ') ? auth.slice(7) : ''
  if (!verifyAgentInternalToken(token)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const { context } = await req.json()
  if (!context) return NextResponse.json({ error: 'context required' }, { status: 400 })

  const prompt = buildPrompt(context)
  try {
    const cheap = await generateWithDeepSeek(prompt)
    if (cheap) return NextResponse.json({ plan: cheap, model: 'deepseek' })
    const plan = await generateWithClaude(prompt)
    return NextResponse.json({ plan, model: 'claude-fallback' })
  } catch (err) {
    return NextResponse.json({ plan: null, error: String(err) })
  }
}
