# ALMA office PC — one-shot ENTRANCE setup (PowerShell 5.1 compatible, ASCII-only).
#
# Run this ONCE on the office PC (paste into a PowerShell window and press Enter).
# It is self-contained and idempotent: it runs to completion locally even if the
# AnyDesk session drops right after you start it.
#
# What it does:
#   1. Reads the shared device password from the existing workroom RTSP line in
#      go2rtc.yaml (entrance uses the SAME password as workroom — no secret in git).
#   2. Probes the entrance camera ONCE to confirm auth before changing anything.
#   3. Backs up go2rtc.yaml and rewrites it with workroom + entrance streams
#      (boss left commented, ready for when its device password is set).
#   4. Writes the listener config + the camera-listen.ps1 script.
#   5. Restarts go2rtc so the new streams load.
#   6. Registers the listener to auto-start at logon and starts it now.
#
# Boss Office Room (192.168.1.191) is intentionally NOT added — set its device
# password later, then uncomment the boss block in go2rtc.yaml (or re-run a boss
# variant of this script).

$ErrorActionPreference = 'Stop'
$Go2rtcDir = 'C:\go2rtc'
$Yaml   = Join-Path $Go2rtcDir 'go2rtc.yaml'
$Ffmpeg = Join-Path $Go2rtcDir 'ffmpeg.exe'

if (-not (Test-Path $Yaml))   { Write-Host "ERROR: $Yaml not found"; return }
if (-not (Test-Path $Ffmpeg)) { Write-Host "ERROR: $Ffmpeg not found"; return }

# --- 1. Derive the shared device password from the workroom stream ----------
$content = Get-Content -Raw $Yaml
$m = [regex]::Match($content, 'rtsp://admin:([^@]+)@192\.168\.1\.228')
if (-not $m.Success) { Write-Host "ERROR: could not read workroom password from go2rtc.yaml"; return }
$Pass = $m.Groups[1].Value
Write-Host "OK: using the shared device password from the workroom stream."

$EntranceUrl = "rtsp://admin:$Pass@192.168.1.147:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif"

# --- 2. Probe entrance ONCE (single attempt; abort on auth failure) ---------
Write-Host "Probing entrance camera (192.168.1.147)..."
$probe = & $Ffmpeg -rtsp_transport tcp -i $EntranceUrl -t 1 -f null - 2>&1
if ($probe -match '401|Unauthorized|Invalid data|Server returned 4|denied') {
    Write-Host "ERROR: entrance auth failed. No changes made. (Check the device password.)"
    return
}
Write-Host "OK: entrance RTSP authenticated."

# --- 3. Backup + rewrite go2rtc.yaml ----------------------------------------
Copy-Item $Yaml "$Yaml.bak" -Force
$newYaml = @"
streams:
  workroom:
    - rtsp://admin:$Pass@192.168.1.228:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
  entrance:
    - rtsp://admin:$Pass@192.168.1.147:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
  # boss:  # TODO: set Boss Office Room (192.168.1.191) device password, then uncomment:
  #   - rtsp://admin:REPLACE_BOSS_PASS@192.168.1.191:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
ffmpeg:
  bin: C:/go2rtc/ffmpeg.exe
"@
Set-Content -Path $Yaml -Value $newYaml -Encoding ASCII
Write-Host "OK: go2rtc.yaml updated (workroom + entrance; boss commented). Backup: go2rtc.yaml.bak"

# --- 4. Listener config + script --------------------------------------------
Set-Content -Path (Join-Path $Go2rtcDir 'listen-rtsp.txt') -Value $EntranceUrl -Encoding ASCII

$listener = @'
# ALMA office PC camera LISTENER (auto-generated by office-pc-setup-entrance.ps1).
$Api        = 'https://alma-erp-six.vercel.app'
$Room       = 'entrance'
$TokenFile  = 'C:\go2rtc\bridge-token.txt'
$RtspFile   = 'C:\go2rtc\listen-rtsp.txt'
$Ffmpeg     = 'C:\go2rtc\ffmpeg.exe'
$ChunkSec   = 6
$SilenceDb  = -45
$Chunk      = "$env:TEMP\alma-listen.wav"

if (-not (Test-Path $TokenFile)) { Write-Host "ERROR: token file not found: $TokenFile"; exit 1 }
if (-not (Test-Path $RtspFile))  { Write-Host "ERROR: rtsp file not found: $RtspFile";   exit 1 }
if (-not (Test-Path $Ffmpeg))    { Write-Host "ERROR: ffmpeg not found: $Ffmpeg";        exit 1 }
$Token = (Get-Content -Raw $TokenFile).Trim()
$Rtsp  = (Get-Content -Raw $RtspFile).Trim()
if ([string]::IsNullOrEmpty($Token)) { Write-Host "ERROR: token file empty"; exit 1 }
if ([string]::IsNullOrEmpty($Rtsp))  { Write-Host "ERROR: rtsp file empty";  exit 1 }
$Headers = @{ Authorization = "Bearer $Token" }
Write-Host "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') camera listener started (room=$Room, chunk=$ChunkSec s)"

function Get-MeanVolumeDb($wav) {
    $out = & $Ffmpeg -hide_banner -i $wav -af volumedetect -f null - 2>&1
    $line = $out | Select-String 'mean_volume:\s*(-?\d+(\.\d+)?) dB'
    if ($line) { return [double]$line.Matches[0].Groups[1].Value }
    return -100
}

while ($true) {
    try {
        if (Test-Path $Chunk) { Remove-Item $Chunk -ErrorAction SilentlyContinue }
        & $Ffmpeg -hide_banner -loglevel error -rtsp_transport tcp -i $Rtsp -t $ChunkSec -vn -ac 1 -ar 16000 -y $Chunk 2>&1 | Out-Null
        if (-not (Test-Path $Chunk)) { Write-Host "$(Get-Date -Format 'HH:mm:ss') no audio captured - retry"; Start-Sleep 5; continue }
        $vol = Get-MeanVolumeDb $Chunk
        if ($vol -lt $SilenceDb) { continue }
        $bytes = [System.IO.File]::ReadAllBytes($Chunk)
        $uri = "$Api/api/assistant/internal/camera-listen?room=$Room"
        $resp = Invoke-RestMethod -Method POST $uri -Headers $Headers -ContentType 'audio/wav' -Body $bytes -TimeoutSec 40
        $stamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
        if ($resp.matched -and $resp.forwarded) { Write-Host "$stamp WAKE + forwarded: $($resp.heard)" }
        elseif ($resp.matched) { Write-Host "$stamp wake word, not forwarded ($($resp.reason)): $($resp.heard)" }
        elseif ($resp.heard) { Write-Host "$stamp heard (no wake word): $($resp.heard)" }
    } catch {
        Write-Host "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') loop error: $($_.Exception.Message)"; Start-Sleep 10
    }
}
'@
Set-Content -Path (Join-Path $Go2rtcDir 'camera-listen.ps1') -Value $listener -Encoding ASCII
Write-Host "OK: camera-listen.ps1 + listen-rtsp.txt written."

# --- 5. Restart go2rtc so the new streams load ------------------------------
Get-Process go2rtc -ErrorAction SilentlyContinue | Stop-Process -Force
Start-Sleep 2
Start-Process -FilePath (Join-Path $Go2rtcDir 'go2rtc.exe') -WorkingDirectory $Go2rtcDir -WindowStyle Minimized
Start-Sleep 3
Write-Host "OK: go2rtc restarted."

# --- 6. Register listener auto-start at logon + start it now ----------------
$listenCmd = "powershell -ExecutionPolicy Bypass -WindowStyle Minimized -File $Go2rtcDir\camera-listen.ps1"
Set-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run' -Name 'alma-camera-listen' -Value $listenCmd
Start-Process -FilePath 'powershell' -ArgumentList "-ExecutionPolicy Bypass -WindowStyle Minimized -File $Go2rtcDir\camera-listen.ps1"
Write-Host "OK: listener registered at logon + started."

# --- 7. Show final go2rtc stream list ---------------------------------------
Start-Sleep 2
try {
    $streams = Invoke-RestMethod -Method GET 'http://localhost:1984/api/streams' -TimeoutSec 10
    Write-Host "go2rtc streams now: $((($streams.PSObject.Properties).Name) -join ', ')"
} catch { Write-Host "note: could not read go2rtc stream list yet (it may still be starting)." }

Write-Host ""
Write-Host "DONE. Entrance camera added and listener running. Boss left for later."
