/**
 * G08 / SPEC-073 — Domain manifest package generator (DEV-TIME ONLY).
 *
 * Reads the committed inventory snapshot (`registry/inventory.data.ts` — pure
 * data, ZERO monolith coupling) and emits `domains.generated.ts`: the 326 tools
 * partitioned into per-domain `DomainPackage`s. This is the deterministic seam
 * that turns the flat monolith into domain packages.
 *
 * Side-effects are seeded here from (mode, domain, risk) with a documented,
 * deterministic mapping; SPEC-075 owns the authoritative classifier + policy
 * hints and a test that these seeds stay consistent with it.
 *
 * Run: npx tsx --tsconfig tsconfig.json \
 *        src/agent/tools/manifests/scripts/build-domain-manifests.ts
 */
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { INVENTORY_ROWS } from '@/agent/tools/registry/inventory.data'
import type { InventoryRow } from '@/agent/tools/registry/inventory.schema'
import { deriveSideEffects } from '../derive-side-effects'
import type { ToolManifest } from '../manifest.schema'

function toManifest(r: InventoryRow): ToolManifest {
  const mode = (r.mode ?? 'read') as ToolManifest['capability']['mode']
  const risk = (r.risk ?? 'low') as ToolManifest['capability']['risk']
  const domain = r.domain ?? 'unclassified'
  return {
    name: r.name,
    domain,
    title: r.name.replace(/_/g, ' '),
    summary: `${mode} tool in the ${domain} domain.`,
    version: '1.0.0',
    status: 'active',
    capability: { mode, risk, sideEffects: deriveSideEffects(mode, domain, risk) },
    io: { inputSchemaId: `${domain}.${r.name}.input` },
    ownership: { team: '@alma/agent', zonePrefix: 'src/agent/tools' },
    routing: { groups: r.groups, pools: r.pools },
  }
}

function build(): Map<string, ToolManifest[]> {
  const byDomain = new Map<string, ToolManifest[]>()
  for (const r of INVENTORY_ROWS) {
    const m = toManifest(r)
    ;(byDomain.get(m.domain) ?? byDomain.set(m.domain, []).get(m.domain)!).push(m)
  }
  for (const list of byDomain.values()) list.sort((a, b) => a.name.localeCompare(b.name))
  return byDomain
}

function render(byDomain: Map<string, ToolManifest[]>): string {
  const domains = [...byDomain.keys()].sort()
  const lines: string[] = []
  lines.push('/**')
  lines.push(' * GENERATED by scripts/build-domain-manifests.ts (G08 / SPEC-073). DO NOT EDIT.')
  lines.push(' *')
  lines.push(' * The monolith surface partitioned into per-domain manifest packages, sourced')
  lines.push(' * from registry/inventory.data.ts. Pure data; no monolith/prisma/model (INV-01).')
  lines.push(' */')
  lines.push("import type { DomainPackage } from './domain-package'")
  lines.push('')
  lines.push('export const DOMAIN_PACKAGES: readonly DomainPackage[] = [')
  for (const domain of domains) {
    const manifests = byDomain.get(domain)!
    lines.push(`  {`)
    lines.push(`    domain: ${JSON.stringify(domain)},`)
    lines.push(`    manifests: [`)
    for (const m of manifests) lines.push(`      ${JSON.stringify(m)},`)
    lines.push(`    ],`)
    lines.push(`  },`)
  }
  lines.push(']')
  lines.push('')
  return lines.join('\n')
}

function main(): void {
  const byDomain = build()
  const out = render(byDomain)
  const target = resolve(process.cwd(), 'src/agent/tools/manifests/domains.generated.ts')
  writeFileSync(target, out, 'utf8')
  const total = [...byDomain.values()].reduce((a, l) => a + l.length, 0)
  // eslint-disable-next-line no-console
  console.error(`[build-domain-manifests] ${byDomain.size} domains, ${total} manifests → ${target}`)
}

main()
